### ISSUE TITLE
ServerWebsite expansion fails on Spigot 1.15.2

### ISSUE THREAD

**Issue by SlimeDog** [Steve-Tech/ServerWebsite#1]
Spigot 1.15.2
Expansion-ServerWebsite_1VrF9uz (version=1.0.0)

PAPI expansion fails to load on server start-up or papi reload. No errors, no indication of an attempt.

**Comment by Steve-Tech** [comment]
Hi, have you installed the actual ServerWebsite plugin (from the [releases page](https://github.com/Steve-Tech/ServerWebsite/releases) or [spigot](https://www.spigotmc.org/resources/serverwebsite.13007/))?

**Comment by SlimeDog** [comment]
No. I should have realized that is a requirement. I will install and retest. Thank you.

**Comment by SlimeDog** [comment]
Mea culpa. Works great. Thanks.
